name: Build Tauri App in linux.yml

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: write-all

env:
  XRAY_BASE_URL: https://github.com/XTLS/Xray-core/releases/download/v25.4.30/

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        arch: [ x64 ]
        include:
          - target: x86_64-unknown-linux-gnu
            xray_zip: Xray-linux-64.zip

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Setup pnpm and Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Set file name and download URL (Unix)
        shell: bash
        run: |
          ZIP_URL="${{ env.XRAY_BASE_URL }}${{ matrix.xray_zip }}"
          wget "$ZIP_URL" -O "${{ matrix.xray_zip }}"
          mkdir -p src-tauri/ray/
          unzip -o "${{ matrix.xray_zip }}" -d src-tauri/ray

      - name: List files in the Xray directory
        run: ls -R src-tauri/ray

      - name: Install dependencies on Linux
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Build Tauri App
        run: pnpm run tauri build --target=${{ matrix.target }}

      - name: List files in the release bundle directory
        run: ls -R src-tauri/target/${{ matrix.target }}/release/bundle

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dary-linux-${{ matrix.arch }}
          path: rc-tauri/target/${{ matrix.target }}/release/bundle/*

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          files: |
            src-tauri/target/${{ matrix.target }}/release/bundle/*/dray_*