name: Build Tauri App in m.yml

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: write-all

env:
  XRAY_VERSION: v25.4.30

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            xray_os: windows
            xray_arch: 64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            xray_os: windows
            xray_arch: arm64-v8a
          - os: macos-latest
            target: x86_64-apple-darwin
            xray_os: macos
            xray_arch: 64
          - os: macos-latest
            target: aarch64-apple-darwin
            xray_os: macos
            xray_arch: arm64-v8a
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            xray_os: linux
            xray_arch: 64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            xray_os: linux
            xray_arch: arm64-v8a

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies on Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          cache-all-crates: true
          cache-on-failure: true

      #      - name: Setup Node.js
      #        uses: actions/setup-node@v4
      #        with:
      #          node-version: 20

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      #      - name: Install Tauri CLI
      #        run: pnpm add -g @tauri-apps/cli

      # Bash 设置变量（Linux/macOS）
      - name: Set file name and download URL (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          FILE_NAME="Xray-${{ matrix.xray_os }}-${{ matrix.xray_arch }}.zip"
          FILE_URL="https://github.com/XTLS/Xray-core/releases/download/${{ env.XRAY_VERSION }}/$FILE_NAME"
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
          echo "FILE_URL=$FILE_URL" >> $GITHUB_ENV
          
          wget "$FILE_URL" -O "$FILE_NAME"
          
          mkdir -p src-tauri/ray/
          unzip -o "$FILE_NAME" -d src-tauri/ray

      # PowerShell 设置变量（Windows）
      - name: Set file name and download URL (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $fileName = "Xray-${{ matrix.xray_os }}-${{ matrix.xray_arch }}.zip"
          $fileUrl = "https://github.com/XTLS/Xray-core/releases/download/${{ env.XRAY_VERSION }}/$fileName"

          echo "FILE_NAME=$fileName" >> $env:GITHUB_ENV
          echo "FILE_URL=$fileUrl" >> $env:GITHUB_ENV

          Invoke-WebRequest -Uri $fileUrl -OutFile $fileName

          New-Item -ItemType Directory -Force -Path src-tauri/ray | Out-Null
          Expand-Archive -Path $fileName -DestinationPath src-tauri/ray -Force

      #      - name: Clean up
      #        run: rm "$FILE_NAME"

      - name: List files in the Xray directory
        run: ls -R src-tauri/ray

      - name: Build Tauri App
        run: pnpm run tauri build --target=${{ matrix.target }}

      - name: List files in the release bundle directory  # Debug step
        run: ls -R src-tauri/target/${{ matrix.target }}/release/bundle/

      #      - name: Upload build artifacts
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: tauri-build-${{ matrix.platform }}-${{ matrix.architecture }}
      #          path: src-tauri/target/release/bundle/*

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{steps.build.outputs.appVersion}}
          name: "Dray v${{steps.build.outputs.appVersion}}"
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            src-tauri/target/${{ matrix.target }}/release/bundle/*/dray_*
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}