name: Tauri Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
#        platform: [windows-latest, macos-latest]
#        architecture: [x86_64, arm64]
        platform: [macos-latest]
        architecture: [x86_64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Tauri CLI
        run: pnpm add -g @tauri-apps/cli

      - name: Install dependencies
        run: pnpm install

      - name: Build Tauri app
        run: pnpm run tauri build

      - name: List files in the release bundle directory  # Debug step
        run: ls -R src-tauri/target/release/bundle/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-${{ matrix.platform }}-${{ matrix.architecture }}
          path: src-tauri/target/release/bundle/*

      - name: Create Release
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/appimage/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
