name: Simple GitHub Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1.0
          name: Release v0.1.0
          body: |
            这是一个测试 Release。
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
